### PR TITLE
Adds changes for repo being renamed

### PR DESCRIPTION
**Pull request by kennethormandy**
This should be merged if the repo is renamed as described in #112:

- `package.json` details updated
- Jekyll `config.yml` updated, so base path is accurate
- GitHub footer link updated to use `config.yml` site-wide variables

### CODE REVIEW

**Comment by jpamental** [comment]
@kennethormandy let me know if you want me to fix the conflict and merge this in. I just pushed up the GA tracking code and was going to bring the latest changes into the 'gh_pages' branch to deploy

**Comment by kennethormandy** [comment]
@jpamental No, thank you though! I will resolve them if we go ahead with the rename.

**Comment by davelab6** [comment]
Let's do the rename :)

**Comment by davelab6** [comment]
I resolved the conflict, and have renamed the repo

**Comment by kennethormandy** [comment]
Thank you!

**Pull request merged**
